Repository CosmoStat/Tutorials, pull requests merged in 2019-07, with the labels that each got.

#1 Santi's tutorials on Numpy and Pandas
  python/Answers.ipynb
  python/Numpy-Intro.ipynb
  python/Pandas-Intro.ipynb
Labels: enhancement

#3 final fixes
  README.md
Labels: enhancement

#4 bug fix
  python/Pythonic.ipynb
Labels: bug

#5 materials for numpy and pandas tutorials
  python/materials/02.05-broadcasting.png
  python/materials/CR_Temp.csv
  python/materials/numpy_indexing.png
Labels: bug, enhancement

#7 Newbranch
  python/Numpy-Intro.ipynb
  python/Scipy-Cosmo.ipynb
  python/materials/Fs8covariance.txt
  python/materials/Fs8dataclean.txt
  python/materials/alldataEz-H0planck-real-H0planck.txt
  python/materials/cosmological_energy_densities.png
  python/materials/planck_cosmic_pie.jpg
Labels: enhancement

#8 final updates
  python/Intro-2.ipynb
  python/Pythonic.ipynb
  python/README.md
  python/Scipy-Cosmo.ipynb
  python/materials/cosmological_energy_densities.png
Labels: enhancement
