Repository CosmoStat/Tutorials, pull requests merged in 2020-04, with the labels that each got.

#26 Tf tuto add link
  README.md
Labels: data science, tutorial request

#29 Added Make/CMake tutorial
  README.md
Labels: carpentries

#30 C plus plus
  Exercises/Practice/ChessGame.pdf
  Exercises/Practice/Exercise2.pdf
  Exercises/Practice/PlaceFile.map
  Exercises/Practice/exercise1.pdf
  Exercises/Solutions/.gitkeep
  Exercises/Solutions/Ex1.1_Array/.gitkeep
  Exercises/Solutions/Ex1.1_Array/array1D.cpp
  Exercises/Solutions/Ex1.1_Array/array2D.cpp
  Exercises/Solutions/Ex1_Cartesian2Spherical/.gitkeep
  Exercises/Solutions/Ex1_Cartesian2Spherical/spherical_coord.cpp
  Exercises/Solutions/Ex2_Functions/.gitkeep
  Exercises/Solutions/Ex2_Functions/functions.cpp
  Exercises/Solutions/Ex3_ClassRectangle/.gitkeep
  Exercises/Solutions/Ex3_ClassRectangle/main.cpp
  Exercises/Solutions/Ex3_ClassRectangle/point.h
  Exercises/Solutions/Ex3_ClassRectangle/rectangle.cpp
  Exercises/Solutions/Ex3_ClassRectangle/rectangle.h
  Exercises/Solutions/Ex4_VirtualsMethods/.gitkeep
  Exercises/Solutions/Ex4_VirtualsMethods/cercle.cpp
  Exercises/Solutions/Ex4_VirtualsMethods/cercle.h
  Exercises/Solutions/Ex4_VirtualsMethods/main.cpp
  Exercises/Solutions/Ex4_VirtualsMethods/point.cpp
  Exercises/Solutions/Ex4_VirtualsMethods/point.h
  Exercises/Solutions/Ex4_VirtualsMethods/rectangle.cpp
  Exercises/Solutions/Ex4_VirtualsMethods/rectangle.h
  Exercises/Solutions/Ex4_VirtualsMethods/shape.h
  Exercises/Solutions/Part1_ExampleUsed/.gitkeep
  Exercises/Solutions/Part1_ExampleUsed/if_example.cpp
  Exercises/Solutions/Part1_ExampleUsed/io_example.cpp
  Exercises/Solutions/Part1_ExampleUsed/loop_example.cpp
  Exercises/Solutions/Part1_ExampleUsed/swapping.cpp
  Exercises/Solutions/Part1_ExampleUsed/switch.cpp
  Exercises/download/.gitkeep
  Exercises/download/Rectangle_Class/.gitkeep
  Exercises/download/Rectangle_Class/main.cpp
  Exercises/download/Rectangle_Class/point.cpp
  Exercises/download/Rectangle_Class/point.h
  Exercises/download/Rectangle_Class/rectangle.h
  Exercises/download/VirtualMethods/.gitkeep
  Exercises/download/VirtualMethods/main.cpp
  Exercises/download/VirtualMethods/point.cpp
  Exercises/download/VirtualMethods/point.h
  Exercises/download/VirtualMethods/rectangle.cpp
  Exercises/download/VirtualMethods/rectangle.h
  README.md
  Tutorial/Part1_Introduction.pdf
  Tutorial/Part2_Classes_Objects.pdf
  Tutorial/Part3_VirtualFunction.pdf
  Tutorial/Part4_Template.pdf
Labels: data science, enhancement

#33 Added C++ tutorial
  README.md
Labels: data science, enhancement
